cursor               #feb876
cursor_text_color    #4b2800

foreground           #efe0d5
background           #19120c
selection_foreground #412c18
selection_background #e2c0a4
url_color            #feb876

# black (neutral dark)
color0  #51443a
color8  #9e8e81

# red (error / tonal red)
color1  #ffb4ab
color9  #93000a

# green (secondary accent)
color2  #e2c0a4
color10 #59422d

# yellow (tertiary accent, warm)
color3  #c1cc99
color11 #424b23

# blue (primary accent)
color4  #feb876
color12 #6a3b02

# magenta (secondary variant, pink/purple)
color5  #c1cc99
color13 #424b23

# cyan (inverse primary / blended accent)
color6  #86521a
color14 #ffdcbf

# white (neutral light)
color7  #d5c3b6
color15 #efe0d5
